name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go
      # action para automatizar o docker
      #setup para utilizar em diferentes arquiteturas
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      #realiza o build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          #usuario e repositorio do github
          tags: luamleiverton/ci_full_cycle:latest
          